[2015-09-22 09:35:17] request.INFO: Matched route "libreame_ingresarSistema" (parameters: "_controller": "Libreame\BackendBundle\Controller\AccesoController::ingresarSistemaAction", "_format": "json", "_route": "libreame_ingresarSistema") [] []
[2015-09-22 09:35:18] request.CRITICAL: Uncaught PHP Exception Doctrine\DBAL\DBALException: "An exception occurred while executing 'INSERT INTO lb_libros (txLibTipoPublica, txLibTitulo, txLibAutores, txLibIdioma, txLibEditorial, txLibEdicionAnio, txLibEdicionNum, txLibEdicionPais, txEdicionDescripcion, txLibCodigoOfic, txLibCodigoOfic13, txLibResumen, txLibTomo, txLibVolumen, txPaginas) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)' with params [0, "El libro de la verdad", "Sin identificar", "espa\u00f1ol", "Sin identificar", "Pendiente", "Sin identificar", "Sin identificar", "Sin identificar", "Sin identificar", "Sin identificar", "Sin identificar", "Sin identificar", "Sin identificar", "Sin identificar"]: SQLSTATE[22001]: String data, right truncated: 1406 Data too long for column 'txLibEdicionNum' at row 1" at C:\xampp\htdocs\Ex4ReadBE\vendor\doctrine\dbal\lib\Doctrine\DBAL\DBALException.php line 91 {"exception":"[object] (Doctrine\\DBAL\\DBALException: An exception occurred while executing 'INSERT INTO lb_libros (txLibTipoPublica, txLibTitulo, txLibAutores, txLibIdioma, txLibEditorial, txLibEdicionAnio, txLibEdicionNum, txLibEdicionPais, txEdicionDescripcion, txLibCodigoOfic, txLibCodigoOfic13, txLibResumen, txLibTomo, txLibVolumen, txPaginas) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)' with params [0, \"El libro de la verdad\", \"Sin identificar\", \"espa\\u00f1ol\", \"Sin identificar\", \"Pendiente\", \"Sin identificar\", \"Sin identificar\", \"Sin identificar\", \"Sin identificar\", \"Sin identificar\", \"Sin identificar\", \"Sin identificar\", \"Sin identificar\", \"Sin identificar\"]:\n\nSQLSTATE[22001]: String data, right truncated: 1406 Data too long for column 'txLibEdicionNum' at row 1 at C:\\xampp\\htdocs\\Ex4ReadBE\\vendor\\doctrine\\dbal\\lib\\Doctrine\\DBAL\\DBALException.php:91, PDOException: SQLSTATE[22001]: String data, right truncated: 1406 Data too long for column 'txLibEdicionNum' at row 1 at C:\\xampp\\htdocs\\Ex4ReadBE\\vendor\\doctrine\\dbal\\lib\\Doctrine\\DBAL\\Statement.php:165)"} []
[2015-09-22 09:36:56] request.INFO: Matched route "libreame_ingresarSistema" (parameters: "_controller": "Libreame\BackendBundle\Controller\AccesoController::ingresarSistemaAction", "_format": "json", "_route": "libreame_ingresarSistema") [] []
[2015-09-22 09:36:57] request.CRITICAL: Uncaught PHP Exception Doctrine\DBAL\DBALException: "An exception occurred while executing 'INSERT INTO lb_libros (txLibTipoPublica, txLibTitulo, txLibAutores, txLibIdioma, txLibEditorial, txLibEdicionAnio, txLibEdicionNum, txLibEdicionPais, txEdicionDescripcion, txLibCodigoOfic, txLibCodigoOfic13, txLibResumen, txLibTomo, txLibVolumen, txPaginas) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)' with params [0, "El libro de la verdad", "Sin identificar", "espa\u00f1ol", "Sin identificar", "Pendiente", "Sin identificar", "Sin identificar", "Sin identificar", "Sin identificar", "Sin identificar", "Sin identificar", "Sin identificar", "Sin identificar", "Sin identificar"]: SQLSTATE[22001]: String data, right truncated: 1406 Data too long for column 'txLibEdicionNum' at row 1" at C:\xampp\htdocs\Ex4ReadBE\vendor\doctrine\dbal\lib\Doctrine\DBAL\DBALException.php line 91 {"exception":"[object] (Doctrine\\DBAL\\DBALException: An exception occurred while executing 'INSERT INTO lb_libros (txLibTipoPublica, txLibTitulo, txLibAutores, txLibIdioma, txLibEditorial, txLibEdicionAnio, txLibEdicionNum, txLibEdicionPais, txEdicionDescripcion, txLibCodigoOfic, txLibCodigoOfic13, txLibResumen, txLibTomo, txLibVolumen, txPaginas) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)' with params [0, \"El libro de la verdad\", \"Sin identificar\", \"espa\\u00f1ol\", \"Sin identificar\", \"Pendiente\", \"Sin identificar\", \"Sin identificar\", \"Sin identificar\", \"Sin identificar\", \"Sin identificar\", \"Sin identificar\", \"Sin identificar\", \"Sin identificar\", \"Sin identificar\"]:\n\nSQLSTATE[22001]: String data, right truncated: 1406 Data too long for column 'txLibEdicionNum' at row 1 at C:\\xampp\\htdocs\\Ex4ReadBE\\vendor\\doctrine\\dbal\\lib\\Doctrine\\DBAL\\DBALException.php:91, PDOException: SQLSTATE[22001]: String data, right truncated: 1406 Data too long for column 'txLibEdicionNum' at row 1 at C:\\xampp\\htdocs\\Ex4ReadBE\\vendor\\doctrine\\dbal\\lib\\Doctrine\\DBAL\\Statement.php:165)"} []
[2015-09-22 09:38:15] request.INFO: Matched route "libreame_ingresarSistema" (parameters: "_controller": "Libreame\BackendBundle\Controller\AccesoController::ingresarSistemaAction", "_format": "json", "_route": "libreame_ingresarSistema") [] []
[2015-09-22 09:38:15] request.CRITICAL: Uncaught PHP Exception Doctrine\ORM\ORMException: "Entity 'Libreame\BackendBundle\Entity\LbGeneros' has no field 'id'. You can therefore not call 'findById' on the entities' repository" at C:\xampp\htdocs\Ex4ReadBE\vendor\doctrine\orm\lib\Doctrine\ORM\ORMException.php line 169 {"exception":"[object] (Doctrine\\ORM\\ORMException: Entity 'Libreame\\BackendBundle\\Entity\\LbGeneros' has no field 'id'. You can therefore not call 'findById' on the entities' repository at C:\\xampp\\htdocs\\Ex4ReadBE\\vendor\\doctrine\\orm\\lib\\Doctrine\\ORM\\ORMException.php:169)"} []
[2015-09-22 09:39:43] request.INFO: Matched route "libreame_ingresarSistema" (parameters: "_controller": "Libreame\BackendBundle\Controller\AccesoController::ingresarSistemaAction", "_format": "json", "_route": "libreame_ingresarSistema") [] []
[2015-09-22 09:39:44] request.CRITICAL: Uncaught PHP Exception Doctrine\ORM\ORMException: "Entity 'Libreame\BackendBundle\Entity\LbGeneros' has no field 'id'. You can therefore not call 'findById' on the entities' repository" at C:\xampp\htdocs\Ex4ReadBE\vendor\doctrine\orm\lib\Doctrine\ORM\ORMException.php line 169 {"exception":"[object] (Doctrine\\ORM\\ORMException: Entity 'Libreame\\BackendBundle\\Entity\\LbGeneros' has no field 'id'. You can therefore not call 'findById' on the entities' repository at C:\\xampp\\htdocs\\Ex4ReadBE\\vendor\\doctrine\\orm\\lib\\Doctrine\\ORM\\ORMException.php:169)"} []
[2015-09-22 09:48:27] request.INFO: Matched route "libreame_ingresarSistema" (parameters: "_controller": "Libreame\BackendBundle\Controller\AccesoController::ingresarSistemaAction", "_format": "json", "_route": "libreame_ingresarSistema") [] []
[2015-09-22 09:48:29] request.CRITICAL: Uncaught PHP Exception Doctrine\ORM\ORMException: "Entity 'Libreame\BackendBundle\Entity\LbGrupos' has no field 'id'. You can therefore not call 'findById' on the entities' repository" at C:\xampp\htdocs\Ex4ReadBE\vendor\doctrine\orm\lib\Doctrine\ORM\ORMException.php line 169 {"exception":"[object] (Doctrine\\ORM\\ORMException: Entity 'Libreame\\BackendBundle\\Entity\\LbGrupos' has no field 'id'. You can therefore not call 'findById' on the entities' repository at C:\\xampp\\htdocs\\Ex4ReadBE\\vendor\\doctrine\\orm\\lib\\Doctrine\\ORM\\ORMException.php:169)"} []
[2015-09-22 09:51:21] request.INFO: Matched route "libreame_ingresarSistema" (parameters: "_controller": "Libreame\BackendBundle\Controller\AccesoController::ingresarSistemaAction", "_format": "json", "_route": "libreame_ingresarSistema") [] []
[2015-09-22 09:51:22] request.CRITICAL: Uncaught PHP Exception Doctrine\DBAL\DBALException: "An exception occurred while executing 'INSERT INTO lb_ofrecidos (inOfrTransac, txOfrObservacion, dbOfrValOferta, dbOfrValAdic, inOfrEjemplar, inOfrOferta) VALUES (?, ?, ?, ?, ?, ?)' with params [null, "esta en buen estado, pero subrayado en varias paginas", "10000", "50000", 5, 1]: SQLSTATE[23000]: Integrity constraint violation: 1048 Column 'inOfrTransac' cannot be null" at C:\xampp\htdocs\Ex4ReadBE\vendor\doctrine\dbal\lib\Doctrine\DBAL\DBALException.php line 91 {"exception":"[object] (Doctrine\\DBAL\\DBALException: An exception occurred while executing 'INSERT INTO lb_ofrecidos (inOfrTransac, txOfrObservacion, dbOfrValOferta, dbOfrValAdic, inOfrEjemplar, inOfrOferta) VALUES (?, ?, ?, ?, ?, ?)' with params [null, \"esta en buen estado, pero subrayado en varias paginas\", \"10000\", \"50000\", 5, 1]:\n\nSQLSTATE[23000]: Integrity constraint violation: 1048 Column 'inOfrTransac' cannot be null at C:\\xampp\\htdocs\\Ex4ReadBE\\vendor\\doctrine\\dbal\\lib\\Doctrine\\DBAL\\DBALException.php:91, PDOException: SQLSTATE[23000]: Integrity constraint violation: 1048 Column 'inOfrTransac' cannot be null at C:\\xampp\\htdocs\\Ex4ReadBE\\vendor\\doctrine\\dbal\\lib\\Doctrine\\DBAL\\Statement.php:165)"} []
[2015-09-22 10:02:12] request.INFO: Matched route "libreame_ingresarSistema" (parameters: "_controller": "Libreame\BackendBundle\Controller\AccesoController::ingresarSistemaAction", "_format": "json", "_route": "libreame_ingresarSistema") [] []
[2015-09-22 10:02:14] request.CRITICAL: Uncaught PHP Exception Doctrine\DBAL\DBALException: "An exception occurred while executing 'INSERT INTO lb_solicitados (inSolTransac, txSolObservacion, dbSolValOferta, dbSolValAdic, inSolEjemplar, inSolOferta, inSolLibro) VALUES (?, ?, ?, ?, ?, ?, ?)' with params [2, "esta en buen estado, pero subrayado en varias paginas", null, "5000", null, 2, 16]: SQLSTATE[23000]: Integrity constraint violation: 1048 Column 'dbSolValOferta' cannot be null" at C:\xampp\htdocs\Ex4ReadBE\vendor\doctrine\dbal\lib\Doctrine\DBAL\DBALException.php line 91 {"exception":"[object] (Doctrine\\DBAL\\DBALException: An exception occurred while executing 'INSERT INTO lb_solicitados (inSolTransac, txSolObservacion, dbSolValOferta, dbSolValAdic, inSolEjemplar, inSolOferta, inSolLibro) VALUES (?, ?, ?, ?, ?, ?, ?)' with params [2, \"esta en buen estado, pero subrayado en varias paginas\", null, \"5000\", null, 2, 16]:\n\nSQLSTATE[23000]: Integrity constraint violation: 1048 Column 'dbSolValOferta' cannot be null at C:\\xampp\\htdocs\\Ex4ReadBE\\vendor\\doctrine\\dbal\\lib\\Doctrine\\DBAL\\DBALException.php:91, PDOException: SQLSTATE[23000]: Integrity constraint violation: 1048 Column 'dbSolValOferta' cannot be null at C:\\xampp\\htdocs\\Ex4ReadBE\\vendor\\doctrine\\dbal\\lib\\Doctrine\\DBAL\\Statement.php:165)"} []
[2015-09-22 10:05:00] request.INFO: Matched route "libreame_ingresarSistema" (parameters: "_controller": "Libreame\BackendBundle\Controller\AccesoController::ingresarSistemaAction", "_format": "json", "_route": "libreame_ingresarSistema") [] []
[2015-09-22 10:05:02] request.CRITICAL: Uncaught PHP Exception Doctrine\DBAL\DBALException: "An exception occurred while executing 'INSERT INTO lb_solicitados (inSolTransac, txSolObservacion, dbSolValOferta, dbSolValAdic, inSolEjemplar, inSolOferta, inSolLibro) VALUES (?, ?, ?, ?, ?, ?, ?)' with params [2, "esta en buen estado, pero subrayado en varias paginas", null, "5000", null, 3, 19]: SQLSTATE[23000]: Integrity constraint violation: 1048 Column 'dbSolValOferta' cannot be null" at C:\xampp\htdocs\Ex4ReadBE\vendor\doctrine\dbal\lib\Doctrine\DBAL\DBALException.php line 91 {"exception":"[object] (Doctrine\\DBAL\\DBALException: An exception occurred while executing 'INSERT INTO lb_solicitados (inSolTransac, txSolObservacion, dbSolValOferta, dbSolValAdic, inSolEjemplar, inSolOferta, inSolLibro) VALUES (?, ?, ?, ?, ?, ?, ?)' with params [2, \"esta en buen estado, pero subrayado en varias paginas\", null, \"5000\", null, 3, 19]:\n\nSQLSTATE[23000]: Integrity constraint violation: 1048 Column 'dbSolValOferta' cannot be null at C:\\xampp\\htdocs\\Ex4ReadBE\\vendor\\doctrine\\dbal\\lib\\Doctrine\\DBAL\\DBALException.php:91, PDOException: SQLSTATE[23000]: Integrity constraint violation: 1048 Column 'dbSolValOferta' cannot be null at C:\\xampp\\htdocs\\Ex4ReadBE\\vendor\\doctrine\\dbal\\lib\\Doctrine\\DBAL\\Statement.php:165)"} []
[2015-09-22 10:09:48] request.INFO: Matched route "libreame_ingresarSistema" (parameters: "_controller": "Libreame\BackendBundle\Controller\AccesoController::ingresarSistemaAction", "_format": "json", "_route": "libreame_ingresarSistema") [] []
[2015-09-22 10:09:50] request.CRITICAL: Uncaught PHP Exception Doctrine\DBAL\DBALException: "An exception occurred while executing 'INSERT INTO lb_solicitados (inSolTransac, txSolObservacion, dbSolValOferta, dbSolValAdic, inSolEjemplar, inSolOferta, inSolLibro) VALUES (?, ?, ?, ?, ?, ?, ?)' with params [2, "esta en buen estado, pero subrayado en varias paginas", null, "5000", null, 4, 22]: SQLSTATE[23000]: Integrity constraint violation: 1048 Column 'dbSolValOferta' cannot be null" at C:\xampp\htdocs\Ex4ReadBE\vendor\doctrine\dbal\lib\Doctrine\DBAL\DBALException.php line 91 {"exception":"[object] (Doctrine\\DBAL\\DBALException: An exception occurred while executing 'INSERT INTO lb_solicitados (inSolTransac, txSolObservacion, dbSolValOferta, dbSolValAdic, inSolEjemplar, inSolOferta, inSolLibro) VALUES (?, ?, ?, ?, ?, ?, ?)' with params [2, \"esta en buen estado, pero subrayado en varias paginas\", null, \"5000\", null, 4, 22]:\n\nSQLSTATE[23000]: Integrity constraint violation: 1048 Column 'dbSolValOferta' cannot be null at C:\\xampp\\htdocs\\Ex4ReadBE\\vendor\\doctrine\\dbal\\lib\\Doctrine\\DBAL\\DBALException.php:91, PDOException: SQLSTATE[23000]: Integrity constraint violation: 1048 Column 'dbSolValOferta' cannot be null at C:\\xampp\\htdocs\\Ex4ReadBE\\vendor\\doctrine\\dbal\\lib\\Doctrine\\DBAL\\Statement.php:165)"} []
[2015-09-22 10:14:44] request.INFO: Matched route "libreame_ingresarSistema" (parameters: "_controller": "Libreame\BackendBundle\Controller\AccesoController::ingresarSistemaAction", "_format": "json", "_route": "libreame_ingresarSistema") [] []
[2015-09-22 10:14:47] request.CRITICAL: Uncaught PHP Exception Doctrine\DBAL\DBALException: "An exception occurred while executing 'INSERT INTO lb_solicitados (inSolTransac, txSolObservacion, dbSolValOferta, dbSolValAdic, inSolEjemplar, inSolOferta, inSolLibro) VALUES (?, ?, ?, ?, ?, ?, ?)' with params [2, "esta en buen estado, pero subrayado en varias paginas", null, "5000", null, 5, 25]: SQLSTATE[23000]: Integrity constraint violation: 1048 Column 'dbSolValOferta' cannot be null" at C:\xampp\htdocs\Ex4ReadBE\vendor\doctrine\dbal\lib\Doctrine\DBAL\DBALException.php line 91 {"exception":"[object] (Doctrine\\DBAL\\DBALException: An exception occurred while executing 'INSERT INTO lb_solicitados (inSolTransac, txSolObservacion, dbSolValOferta, dbSolValAdic, inSolEjemplar, inSolOferta, inSolLibro) VALUES (?, ?, ?, ?, ?, ?, ?)' with params [2, \"esta en buen estado, pero subrayado en varias paginas\", null, \"5000\", null, 5, 25]:\n\nSQLSTATE[23000]: Integrity constraint violation: 1048 Column 'dbSolValOferta' cannot be null at C:\\xampp\\htdocs\\Ex4ReadBE\\vendor\\doctrine\\dbal\\lib\\Doctrine\\DBAL\\DBALException.php:91, PDOException: SQLSTATE[23000]: Integrity constraint violation: 1048 Column 'dbSolValOferta' cannot be null at C:\\xampp\\htdocs\\Ex4ReadBE\\vendor\\doctrine\\dbal\\lib\\Doctrine\\DBAL\\Statement.php:165)"} []
[2015-09-22 10:17:49] request.INFO: Matched route "libreame_ingresarSistema" (parameters: "_controller": "Libreame\BackendBundle\Controller\AccesoController::ingresarSistemaAction", "_format": "json", "_route": "libreame_ingresarSistema") [] []
[2015-09-22 10:17:49] request.CRITICAL: Uncaught PHP Exception Doctrine\DBAL\DBALException: "An exception occurred while executing 'INSERT INTO lb_solicitados (inSolTransac, txSolObservacion, dbSolValOferta, dbSolValAdic, inSolEjemplar, inSolOferta, inSolLibro) VALUES (?, ?, ?, ?, ?, ?, ?)' with params [2, "esta en buen estado, pero subrayado en varias paginas", null, "5000", null, 6, 28]: SQLSTATE[23000]: Integrity constraint violation: 1048 Column 'dbSolValOferta' cannot be null" at C:\xampp\htdocs\Ex4ReadBE\vendor\doctrine\dbal\lib\Doctrine\DBAL\DBALException.php line 91 {"exception":"[object] (Doctrine\\DBAL\\DBALException: An exception occurred while executing 'INSERT INTO lb_solicitados (inSolTransac, txSolObservacion, dbSolValOferta, dbSolValAdic, inSolEjemplar, inSolOferta, inSolLibro) VALUES (?, ?, ?, ?, ?, ?, ?)' with params [2, \"esta en buen estado, pero subrayado en varias paginas\", null, \"5000\", null, 6, 28]:\n\nSQLSTATE[23000]: Integrity constraint violation: 1048 Column 'dbSolValOferta' cannot be null at C:\\xampp\\htdocs\\Ex4ReadBE\\vendor\\doctrine\\dbal\\lib\\Doctrine\\DBAL\\DBALException.php:91, PDOException: SQLSTATE[23000]: Integrity constraint violation: 1048 Column 'dbSolValOferta' cannot be null at C:\\xampp\\htdocs\\Ex4ReadBE\\vendor\\doctrine\\dbal\\lib\\Doctrine\\DBAL\\Statement.php:165)"} []
[2015-09-22 10:20:08] request.INFO: Matched route "libreame_ingresarSistema" (parameters: "_controller": "Libreame\BackendBundle\Controller\AccesoController::ingresarSistemaAction", "_format": "json", "_route": "libreame_ingresarSistema") [] []
[2015-09-22 10:20:09] request.CRITICAL: Uncaught PHP Exception Doctrine\DBAL\DBALException: "An exception occurred while executing 'INSERT INTO lb_solicitados (inSolTransac, txSolObservacion, dbSolValOferta, dbSolValAdic, inSolEjemplar, inSolOferta, inSolLibro) VALUES (?, ?, ?, ?, ?, ?, ?)' with params [2, "esta en buen estado, pero subrayado en varias paginas", null, "5000", null, 7, 31]: SQLSTATE[23000]: Integrity constraint violation: 1048 Column 'dbSolValOferta' cannot be null" at C:\xampp\htdocs\Ex4ReadBE\vendor\doctrine\dbal\lib\Doctrine\DBAL\DBALException.php line 91 {"exception":"[object] (Doctrine\\DBAL\\DBALException: An exception occurred while executing 'INSERT INTO lb_solicitados (inSolTransac, txSolObservacion, dbSolValOferta, dbSolValAdic, inSolEjemplar, inSolOferta, inSolLibro) VALUES (?, ?, ?, ?, ?, ?, ?)' with params [2, \"esta en buen estado, pero subrayado en varias paginas\", null, \"5000\", null, 7, 31]:\n\nSQLSTATE[23000]: Integrity constraint violation: 1048 Column 'dbSolValOferta' cannot be null at C:\\xampp\\htdocs\\Ex4ReadBE\\vendor\\doctrine\\dbal\\lib\\Doctrine\\DBAL\\DBALException.php:91, PDOException: SQLSTATE[23000]: Integrity constraint violation: 1048 Column 'dbSolValOferta' cannot be null at C:\\xampp\\htdocs\\Ex4ReadBE\\vendor\\doctrine\\dbal\\lib\\Doctrine\\DBAL\\Statement.php:165)"} []
[2015-09-22 10:29:03] request.INFO: Matched route "libreame_ingresarSistema" (parameters: "_controller": "Libreame\BackendBundle\Controller\AccesoController::ingresarSistemaAction", "_format": "json", "_route": "libreame_ingresarSistema") [] []
[2015-09-22 10:29:05] request.CRITICAL: Uncaught PHP Exception Doctrine\ORM\ORMException: "The EntityManager is closed." at C:\xampp\htdocs\Ex4ReadBE\vendor\doctrine\orm\lib\Doctrine\ORM\ORMException.php line 129 {"exception":"[object] (Doctrine\\ORM\\ORMException: The EntityManager is closed. at C:\\xampp\\htdocs\\Ex4ReadBE\\vendor\\doctrine\\orm\\lib\\Doctrine\\ORM\\ORMException.php:129)"} []
[2015-09-22 10:30:20] request.INFO: Matched route "libreame_ingresarSistema" (parameters: "_controller": "Libreame\BackendBundle\Controller\AccesoController::ingresarSistemaAction", "_format": "json", "_route": "libreame_ingresarSistema") [] []
[2015-09-22 10:30:21] request.CRITICAL: Uncaught PHP Exception Doctrine\ORM\ORMException: "The EntityManager is closed." at C:\xampp\htdocs\Ex4ReadBE\vendor\doctrine\orm\lib\Doctrine\ORM\ORMException.php line 129 {"exception":"[object] (Doctrine\\ORM\\ORMException: The EntityManager is closed. at C:\\xampp\\htdocs\\Ex4ReadBE\\vendor\\doctrine\\orm\\lib\\Doctrine\\ORM\\ORMException.php:129)"} []
[2015-09-22 10:33:14] request.INFO: Matched route "libreame_ingresarSistema" (parameters: "_controller": "Libreame\BackendBundle\Controller\AccesoController::ingresarSistemaAction", "_format": "json", "_route": "libreame_ingresarSistema") [] []
[2015-09-22 10:33:14] request.CRITICAL: Uncaught PHP Exception Doctrine\ORM\ORMInvalidArgumentException: "A new entity was found through the relationship 'Libreame\BackendBundle\Entity\LbGeneroslibros#inglilibro' that was not configured to cascade persist operations for entity: Libreame\BackendBundle\Entity\LbLibros@000000004904407100000000771130dc. To solve this issue: Either explicitly call EntityManager#persist() on this unknown entity or configure cascade persist  this association in the mapping for example @ManyToOne(..,cascade={"persist"}). If you cannot find out which entity causes the problem implement 'Libreame\BackendBundle\Entity\LbLibros#__toString()' to get a clue." at C:\xampp\htdocs\Ex4ReadBE\vendor\doctrine\orm\lib\Doctrine\ORM\ORMInvalidArgumentException.php line 91 {"exception":"[object] (Doctrine\\ORM\\ORMInvalidArgumentException: A new entity was found through the relationship 'Libreame\\BackendBundle\\Entity\\LbGeneroslibros#inglilibro' that was not configured to cascade persist operations for entity: Libreame\\BackendBundle\\Entity\\LbLibros@000000004904407100000000771130dc. To solve this issue: Either explicitly call EntityManager#persist() on this unknown entity or configure cascade persist  this association in the mapping for example @ManyToOne(..,cascade={\"persist\"}). If you cannot find out which entity causes the problem implement 'Libreame\\BackendBundle\\Entity\\LbLibros#__toString()' to get a clue. at C:\\xampp\\htdocs\\Ex4ReadBE\\vendor\\doctrine\\orm\\lib\\Doctrine\\ORM\\ORMInvalidArgumentException.php:91)"} []
[2015-09-22 10:35:55] request.INFO: Matched route "libreame_ingresarSistema" (parameters: "_controller": "Libreame\BackendBundle\Controller\AccesoController::ingresarSistemaAction", "_format": "json", "_route": "libreame_ingresarSistema") [] []
[2015-09-22 10:35:55] request.CRITICAL: Uncaught PHP Exception Doctrine\ORM\ORMInvalidArgumentException: "A new entity was found through the relationship 'Libreame\BackendBundle\Entity\LbGeneroslibros#inglilibro' that was not configured to cascade persist operations for entity: Libreame\BackendBundle\Entity\LbLibros@000000005361bfe40000000065fd79c1. To solve this issue: Either explicitly call EntityManager#persist() on this unknown entity or configure cascade persist  this association in the mapping for example @ManyToOne(..,cascade={"persist"}). If you cannot find out which entity causes the problem implement 'Libreame\BackendBundle\Entity\LbLibros#__toString()' to get a clue." at C:\xampp\htdocs\Ex4ReadBE\vendor\doctrine\orm\lib\Doctrine\ORM\ORMInvalidArgumentException.php line 91 {"exception":"[object] (Doctrine\\ORM\\ORMInvalidArgumentException: A new entity was found through the relationship 'Libreame\\BackendBundle\\Entity\\LbGeneroslibros#inglilibro' that was not configured to cascade persist operations for entity: Libreame\\BackendBundle\\Entity\\LbLibros@000000005361bfe40000000065fd79c1. To solve this issue: Either explicitly call EntityManager#persist() on this unknown entity or configure cascade persist  this association in the mapping for example @ManyToOne(..,cascade={\"persist\"}). If you cannot find out which entity causes the problem implement 'Libreame\\BackendBundle\\Entity\\LbLibros#__toString()' to get a clue. at C:\\xampp\\htdocs\\Ex4ReadBE\\vendor\\doctrine\\orm\\lib\\Doctrine\\ORM\\ORMInvalidArgumentException.php:91)"} []
[2015-09-22 10:36:27] request.INFO: Matched route "libreame_ingresarSistema" (parameters: "_controller": "Libreame\BackendBundle\Controller\AccesoController::ingresarSistemaAction", "_format": "json", "_route": "libreame_ingresarSistema") [] []
[2015-09-22 10:36:27] request.CRITICAL: Uncaught PHP Exception Doctrine\ORM\ORMInvalidArgumentException: "A new entity was found through the relationship 'Libreame\BackendBundle\Entity\LbGeneroslibros#inglilibro' that was not configured to cascade persist operations for entity: Libreame\BackendBundle\Entity\LbLibros@0000000040dafa5b00000000769f5169. To solve this issue: Either explicitly call EntityManager#persist() on this unknown entity or configure cascade persist  this association in the mapping for example @ManyToOne(..,cascade={"persist"}). If you cannot find out which entity causes the problem implement 'Libreame\BackendBundle\Entity\LbLibros#__toString()' to get a clue." at C:\xampp\htdocs\Ex4ReadBE\vendor\doctrine\orm\lib\Doctrine\ORM\ORMInvalidArgumentException.php line 91 {"exception":"[object] (Doctrine\\ORM\\ORMInvalidArgumentException: A new entity was found through the relationship 'Libreame\\BackendBundle\\Entity\\LbGeneroslibros#inglilibro' that was not configured to cascade persist operations for entity: Libreame\\BackendBundle\\Entity\\LbLibros@0000000040dafa5b00000000769f5169. To solve this issue: Either explicitly call EntityManager#persist() on this unknown entity or configure cascade persist  this association in the mapping for example @ManyToOne(..,cascade={\"persist\"}). If you cannot find out which entity causes the problem implement 'Libreame\\BackendBundle\\Entity\\LbLibros#__toString()' to get a clue. at C:\\xampp\\htdocs\\Ex4ReadBE\\vendor\\doctrine\\orm\\lib\\Doctrine\\ORM\\ORMInvalidArgumentException.php:91)"} []
[2015-09-22 10:37:46] request.INFO: Matched route "libreame_ingresarSistema" (parameters: "_controller": "Libreame\BackendBundle\Controller\AccesoController::ingresarSistemaAction", "_format": "json", "_route": "libreame_ingresarSistema") [] []
[2015-09-22 10:37:46] request.CRITICAL: Uncaught PHP Exception Doctrine\ORM\ORMInvalidArgumentException: "A new entity was found through the relationship 'Libreame\BackendBundle\Entity\LbGeneroslibros#inglilibro' that was not configured to cascade persist operations for entity: Libreame\BackendBundle\Entity\LbLibros@00000000494f344d000000007d0abc36. To solve this issue: Either explicitly call EntityManager#persist() on this unknown entity or configure cascade persist  this association in the mapping for example @ManyToOne(..,cascade={"persist"}). If you cannot find out which entity causes the problem implement 'Libreame\BackendBundle\Entity\LbLibros#__toString()' to get a clue." at C:\xampp\htdocs\Ex4ReadBE\vendor\doctrine\orm\lib\Doctrine\ORM\ORMInvalidArgumentException.php line 91 {"exception":"[object] (Doctrine\\ORM\\ORMInvalidArgumentException: A new entity was found through the relationship 'Libreame\\BackendBundle\\Entity\\LbGeneroslibros#inglilibro' that was not configured to cascade persist operations for entity: Libreame\\BackendBundle\\Entity\\LbLibros@00000000494f344d000000007d0abc36. To solve this issue: Either explicitly call EntityManager#persist() on this unknown entity or configure cascade persist  this association in the mapping for example @ManyToOne(..,cascade={\"persist\"}). If you cannot find out which entity causes the problem implement 'Libreame\\BackendBundle\\Entity\\LbLibros#__toString()' to get a clue. at C:\\xampp\\htdocs\\Ex4ReadBE\\vendor\\doctrine\\orm\\lib\\Doctrine\\ORM\\ORMInvalidArgumentException.php:91)"} []
[2015-09-22 10:39:06] request.INFO: Matched route "libreame_ingresarSistema" (parameters: "_controller": "Libreame\BackendBundle\Controller\AccesoController::ingresarSistemaAction", "_format": "json", "_route": "libreame_ingresarSistema") [] []
[2015-09-22 10:39:08] request.CRITICAL: Uncaught PHP Exception Doctrine\ORM\ORMException: "The EntityManager is closed." at C:\xampp\htdocs\Ex4ReadBE\vendor\doctrine\orm\lib\Doctrine\ORM\ORMException.php line 129 {"exception":"[object] (Doctrine\\ORM\\ORMException: The EntityManager is closed. at C:\\xampp\\htdocs\\Ex4ReadBE\\vendor\\doctrine\\orm\\lib\\Doctrine\\ORM\\ORMException.php:129)"} []
[2015-09-22 10:40:07] request.INFO: Matched route "libreame_ingresarSistema" (parameters: "_controller": "Libreame\BackendBundle\Controller\AccesoController::ingresarSistemaAction", "_format": "json", "_route": "libreame_ingresarSistema") [] []
[2015-09-22 10:40:07] request.CRITICAL: Uncaught PHP Exception Doctrine\ORM\ORMException: "The EntityManager is closed." at C:\xampp\htdocs\Ex4ReadBE\vendor\doctrine\orm\lib\Doctrine\ORM\ORMException.php line 129 {"exception":"[object] (Doctrine\\ORM\\ORMException: The EntityManager is closed. at C:\\xampp\\htdocs\\Ex4ReadBE\\vendor\\doctrine\\orm\\lib\\Doctrine\\ORM\\ORMException.php:129)"} []
[2015-09-23 09:03:35] request.INFO: Matched route "libreame_ingresarSistema" (parameters: "_controller": "Libreame\BackendBundle\Controller\AccesoController::ingresarSistemaAction", "_format": "json", "_route": "libreame_ingresarSistema") [] []
[2015-09-23 09:03:36] request.CRITICAL: Uncaught PHP Exception Doctrine\ORM\ORMInvalidArgumentException: "A new entity was found through the relationship 'Libreame\BackendBundle\Entity\LbSolicitados#insollibro' that was not configured to cascade persist operations for entity: Libreame\BackendBundle\Entity\LbLibros@0000000022842fa100000000756d3a9d. To solve this issue: Either explicitly call EntityManager#persist() on this unknown entity or configure cascade persist  this association in the mapping for example @ManyToOne(..,cascade={"persist"}). If you cannot find out which entity causes the problem implement 'Libreame\BackendBundle\Entity\LbLibros#__toString()' to get a clue." at C:\xampp\htdocs\Ex4ReadBE\vendor\doctrine\orm\lib\Doctrine\ORM\ORMInvalidArgumentException.php line 91 {"exception":"[object] (Doctrine\\ORM\\ORMInvalidArgumentException: A new entity was found through the relationship 'Libreame\\BackendBundle\\Entity\\LbSolicitados#insollibro' that was not configured to cascade persist operations for entity: Libreame\\BackendBundle\\Entity\\LbLibros@0000000022842fa100000000756d3a9d. To solve this issue: Either explicitly call EntityManager#persist() on this unknown entity or configure cascade persist  this association in the mapping for example @ManyToOne(..,cascade={\"persist\"}). If you cannot find out which entity causes the problem implement 'Libreame\\BackendBundle\\Entity\\LbLibros#__toString()' to get a clue. at C:\\xampp\\htdocs\\Ex4ReadBE\\vendor\\doctrine\\orm\\lib\\Doctrine\\ORM\\ORMInvalidArgumentException.php:91)"} []
[2015-09-23 09:05:17] request.INFO: Matched route "libreame_ingresarSistema" (parameters: "_controller": "Libreame\BackendBundle\Controller\AccesoController::ingresarSistemaAction", "_format": "json", "_route": "libreame_ingresarSistema") [] []
[2015-09-23 09:05:18] request.CRITICAL: Uncaught PHP Exception Doctrine\ORM\ORMInvalidArgumentException: "A new entity was found through the relationship 'Libreame\BackendBundle\Entity\LbSolicitados#insollibro' that was not configured to cascade persist operations for entity: Libreame\BackendBundle\Entity\LbLibros@0000000009a753c2000000004ba0e48c. To solve this issue: Either explicitly call EntityManager#persist() on this unknown entity or configure cascade persist  this association in the mapping for example @ManyToOne(..,cascade={"persist"}). If you cannot find out which entity causes the problem implement 'Libreame\BackendBundle\Entity\LbLibros#__toString()' to get a clue." at C:\xampp\htdocs\Ex4ReadBE\vendor\doctrine\orm\lib\Doctrine\ORM\ORMInvalidArgumentException.php line 91 {"exception":"[object] (Doctrine\\ORM\\ORMInvalidArgumentException: A new entity was found through the relationship 'Libreame\\BackendBundle\\Entity\\LbSolicitados#insollibro' that was not configured to cascade persist operations for entity: Libreame\\BackendBundle\\Entity\\LbLibros@0000000009a753c2000000004ba0e48c. To solve this issue: Either explicitly call EntityManager#persist() on this unknown entity or configure cascade persist  this association in the mapping for example @ManyToOne(..,cascade={\"persist\"}). If you cannot find out which entity causes the problem implement 'Libreame\\BackendBundle\\Entity\\LbLibros#__toString()' to get a clue. at C:\\xampp\\htdocs\\Ex4ReadBE\\vendor\\doctrine\\orm\\lib\\Doctrine\\ORM\\ORMInvalidArgumentException.php:91)"} []
